# Generated by Django 3.2 on 2022-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_personfilmwork_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
